spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/todolist

spring.datasource.username=postgres

spring.datasource.password=rafa_2006#

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

jwt.secret=ZmQ3MjM0ZmY2YjY4Y2Y5MzE0N2Y5YjFkYjQ4N2M1NzQ=
